# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'YapTaskQueueSpecTest' do

  pod 'YapTaskQueue', :path => '../YapTaskQueue.podspec'

end

target 'YapTaskQueueSpecTestTests' do

end
