
osx_image: xcode9.0
language: objective-c

before_install:
    - gem install cocoapods
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint
    - cd Demo
    - pod update
    - xctool -workspace ConsoleDemo.xcworkspace -scheme 'ConsoleDemo' -configuration Release -sdk iphonesimulator -arch i386 build
