language: objective-c
osx_image: xcode11.1

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 8 (13" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID

install:
  - bash ./scripts/build-all.sh
  - bundle install
  - bundle exec pod install --project-directory=Tests/iOS/
  - bundle exec pod install --project-directory=Tests/macOS/  

script:
  - set -o pipefail
  - xcodebuild -workspace Tests/iOS/OTRKit.xcworkspace -scheme OTRKitTestsiOS -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c
  - xcodebuild -workspace Tests/macOS/OTRKit.xcworkspace -scheme OTRKitTestsMac -sdk macosx -destination 'platform=OS X,arch=x86_64' test | xcpretty -c
