language: objective-c
osx_image: xcode11.1

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 8 (13" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - bash ./scripts/build-all.sh

install:
  - cd Tests/iOS
  - bundle install
  - bundle exec pod install
  - cd ../macOS
  - bundle install
  - bundle exec pod install

script:
  - travis_retry xcodebuild -workspace CPAProxy.xcworkspace -scheme CPAProxyTests -sdk iphonesimulator -arch x86_64 test | xcpretty -c
  - cd ../iOS
  - travis_retry xcodebuild -workspace CPAProxy.xcworkspace -scheme CPAProxyTests -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c
