language: objective-c
osx_image: xcode8.2

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 6 (10.2" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

install:
  - cd Tests
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Mac
  - cd ../

script:
  - set -o pipefail
  - xcodebuild -workspace ./Tests/iOS/ProxyKit.xcworkspace -scheme ProxyKitTestsiOS -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c
  - xcodebuild -workspace ./Tests/Mac/ProxyKit.xcworkspace -scheme ProxyKitTestsMac -sdk macosx -arch x86_64 test | xcpretty -c
