source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'XMPPFrameworkTests' do

  pod "XMPPFramework", :path => "../../"

end

target 'XMPPFrameworkSwiftTests' do

  pod "XMPPFramework/Swift", :path => "../../"

end

